name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_wallhaven:

    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild -workspace IncubationCenter.xcworkspace -scheme Wallhaven -configuration Debug -destination "generic/platform=iOS"
