name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  Wallhaven:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Archive
        run: |
          xcodebuild archive -workspace IncubationCenter.xcworkspace -scheme Wallhaven -configuration Release -destination "generic/platform=iOS" -archivePath "Archives/Wallhaven" -quiet CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO
      - name: Generate files
        run: |
          pushd Archives
          mkdir Payload
          cp -r Wallhaven.xcarchive/Products/Applications/Wallhaven.app Payload/
          rm Payload/Wallhaven.app/Frameworks/libswift_Concurrency.dylib
          zip -r Wallhaven.Unsigned.ipa ./Payload
          cp -r Wallhaven.xcarchive/dSYMs dSYMs
          popd
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Archives/Wallhaven.ipa
            Archives/Wallhaven.dSYMs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
